=== rbordel2102/XMLRepo/Act 4.3/Jugueteria/jugueteria.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
 <xs:element name="jugueteria">
  <xs:complexType>
      <xs:sequence>
          <xs:element name="barbie" maxOccurs="unbounded">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="codigo" type="xs:string"/>
                <xs:element name="aÃ±o" type="xs:integer"/>
                <xs:element name="modelo" type="xs:string"/>
                <xs:element name="comercializacion" type="xs:string"/>
                <xs:element name="fabricacion" type="xs:integer"/>
                <xs:element name="publico_edad" type="xs:integer"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
      </xs:sequence>
  </xs:complexType>
 </xs:element>
</xs:schema>

=== rbordel2102/XMLRepo/Act 4.3/Jugueteria/jugueteria_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE jugueteria>
<jugueteria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="jugueteria.xsd">

 <barbie>
   <codigo>123ASD</codigo>
   <año>2020</año>
   <modelo>Con mascarilla</modelo>
   <comercializacion>America</comercializacion>
   <fabricacion>150000</fabricacion>
   <publico_edad>10</publico_edad>
 </barbie>

 <barbie>
    <codigo>540KLM</codigo>
    <año>2005</año>
    <modelo>Al parque</modelo>
    <comercializacion>Asia</comercializacion>
    <fabricacion>450000</fabricacion>
    <publico_edad>10</publico_edad>
  </barbie>

  <barbie>
    <codigo>789HBJ</codigo>
    <año>2024</año>
    <modelo>Discoteca</modelo>
    <comercializacion>Europa</comercializacion>
    <fabricacion>250000</fabricacion>
    <publico_edad>16</publico_edad>
   </barbie>
</jugueteria>
