=== rbordel2102/XMLRepo/Act 4.4/Clientes/clientes.dtd
<!ELEMENT Gestoria (Sede*)>
<!ATTLIST Gestoria>

<!ELEMENT Sede (NombreEmpleado, FechaAlta, Cliente*)>
<!ATTLIST Sede codigo CDATA #REQUIRED>

<!ELEMENT NombreEmpleado (#PCDATA)>
<!ELEMENT FechaAlta (#PCDATA)>

<!ELEMENT Cliente (Descripcion, NumViviendas, vivienda*)>
<!ATTLIST Cliente codigo CDATA #REQUIRED>

<!ELEMENT Descripcion (#PCDATA)>
<!ELEMENT NumViviendas (#PCDATA)>

<!ELEMENT vivienda (CosteVivienda, Resumen, PlazoAlta)>
<!ATTLIST vivienda id CDATA #REQUIRED>

<!ELEMENT CosteVivienda (#PCDATA)>
<!ELEMENT Resumen (#PCDATA)>
<!ELEMENT PlazoAlta (#PCDATA)>

=== rbordel2102/XMLRepo/Act 4.4/Clientes/clientes_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Gestoria SYSTEM "./clientes.dtd">
<Gestoria>

    <Sede codigo="M8958438">

        <NombreEmpleado>Empleado1</NombreEmpleado>
        <FechaAlta>2024-01-22</FechaAlta>

        <Cliente codigo="ABC-123">
            <Descripcion>Solvente</Descripcion>
            <NumViviendas>2</NumViviendas>
            <vivienda id="001" >
                <CosteVivienda>200000</CosteVivienda>
                <Resumen>Vivienda 1: Chalet, Vivienda 2: Chalet</Resumen>
                <PlazoAlta>2024-06-22</PlazoAlta>
            </vivienda>
        </Cliente>
        

        <Cliente codigo="DEF-456">
                <Descripcion>Insolvente</Descripcion>
                <NumViviendas>1</NumViviendas>
                <vivienda id="002" >
                    <CosteVivienda>50000</CosteVivienda>
                    <Resumen>Vivienda 1: Piso</Resumen>
                    <PlazoAlta>2023-02-21</PlazoAlta>
                </vivienda>
        </Cliente>

    </Sede>
    
</Gestoria>
