=== rbordel2102/XMLRepo/Act 4.4/Vendedor/vendedor.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="Tienda">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Sucursal" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="NombreVendedor" type="xs:string"/>
                            <xs:element name="FechaContratacion" type="xs:date"/>
                            <xs:element name="Producto" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Descripcion" type="xs:string"/>
                                        <xs:element name="Precio" type="xs:decimal"/>
                                        <xs:element name="Stock" type="xs:int"/>
                                    </xs:sequence>
                                    <xs:attribute name="codigo" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="codigo" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== rbordel2102/XMLRepo/Act 4.4/Vendedor/vendedor__xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Tienda>
<Tienda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vendedor.xsd">
    <Sucursal codigo="S001">

        <NombreVendedor>Ignacio</NombreVendedor>
        <FechaContratacion>2024-01-22</FechaContratacion>

        <Producto codigo="P001">
            <Descripcion>Camisa azul</Descripcion>
            <Precio>50</Precio>
            <Stock>100</Stock>
        </Producto>

        <Producto codigo="P002">
            <Descripcion>Pantal√≥n negro</Descripcion>
            <Precio>75</Precio>
            <Stock>50</Stock>
        </Producto>

    </Sucursal>
    
</Tienda>
