=== rbordel2102/XMLRepo/Act 4.4/Vendedor/vendedor.dtd
<!ELEMENT Tienda (Sucursal*)>
<!ATTLIST Tienda>

<!ELEMENT Sucursal (NombreVendedor, FechaContratacion, Producto*)>
<!ATTLIST Sucursal codigo CDATA #REQUIRED>

<!ELEMENT NombreVendedor (#PCDATA)>
<!ELEMENT FechaContratacion (#PCDATA)>

<!ELEMENT Producto (Descripcion, Precio, Stock)>
<!ATTLIST Producto codigo CDATA #REQUIRED>

<!ELEMENT Descripcion (#PCDATA)>
<!ELEMENT Precio (#PCDATA)>
<!ELEMENT Stock (#PCDATA)>

=== rbordel2102/XMLRepo/Act 4.4/Vendedor/vendedor_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Tienda SYSTEM "./vendedor.dtd">
<Tienda>
    <Sucursal codigo="S001">

        <NombreVendedor>Ignacio</NombreVendedor>
        <FechaContratacion>2024-01-22</FechaContratacion>

        <Producto codigo="P001">
            <Descripcion>Camisa azul</Descripcion>
            <Precio>50</Precio>
            <Stock>100</Stock>
        </Producto>

        <Producto codigo="P002">
            <Descripcion>Pantal√≥n negro</Descripcion>
            <Precio>75</Precio>
            <Stock>50</Stock>
        </Producto>

    </Sucursal>
    
</Tienda>
