=== rbordel2102/XMLRepo/Act 4.1/Videoclub/videoclub.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
   <xs:element name="videoclub">
       <xs:complexType>
           <xs:sequence>
               <xs:element name="pelicula" maxOccurs="unbounded">
                  <xs:complexType>
                      <xs:sequence>
                          <xs:element name="codigoPelicula" type="xs:integer"/>
                          <xs:element name="director" type="xs:string"/>
                          <xs:element name="titulo" type="xs:string"/>
                          <xs:element name="duracion" type="xs:string"/>
                          <xs:element name="genero" type="xs:string"/>
                          <xs:element name="anoPublicacion" type="xs:integer"/>
                          <xs:element name="formato" type="xs:string"/>
                      </xs:sequence>
                  </xs:complexType>
               </xs:element>
           </xs:sequence>
       </xs:complexType>
   </xs:element>
</xs:schema>

=== rbordel2102/XMLRepo/Act 4.1/Videoclub/videoclub_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE videoclub>

<videoclub xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="videoclub.xsd">

       <pelicula>
           <codigoPelicula>1</codigoPelicula>
           <director>
               Christopher Nolan
           </director>
           <titulo>
               Inception
           </titulo>
           <duracion>
               148 minutos
           </duracion>
           <genero>
               Ciencia ficción
           </genero>
           <anoPublicacion>
               2010
           </anoPublicacion>
           <formato>
               DVD
           </formato>
       </pelicula>

       <pelicula>
        <codigoPelicula>2</codigoPelicula>
        <director>
            Quentin Tarantino
        </director>
        <titulo>
            Reservoir Dogs
        </titulo>
        <duracion>
            99 minutos
        </duracion>
        <genero>
            Drama, crimen
        </genero>
        <anoPublicacion>
            1992
        </anoPublicacion>
        <formato>
            Blu-ray
        </formato>
     </pelicula>
     
     <pelicula>
        <codigoPelicula>3</codigoPelicula>
        <director>
            Francis Ford Coppola
        </director>
        <titulo>
            Apocalypse Now
        </titulo>
        <duracion>
            138 minutos
        </duracion>
        <genero>
            Guerra, drama
        </genero>
        <anoPublicacion>
            1979
        </anoPublicacion>
        <formato>
            DVD
        </formato>
     </pelicula>
     
     <pelicula>
        <codigoPelicula>4</codigoPelicula>
        <director>
            Stanley Kubrick
        </director>
        <titulo>
            2001: Una odisea del espacio
        </titulo>
        <duracion>
            149 minutos
        </duracion>
        <genero>
            Ciencia ficción
        </genero>
        <anoPublicacion>
            1968
        </anoPublicacion>
        <formato>
            Blu-ray
        </formato>
     </pelicula>
     
     <pelicula>
        <codigoPelicula>5</codigoPelicula>
        <director>
            Alfred Hitchcock
        </director>
        <titulo>
            Psicosis
        </titulo>
        <duracion>
            107 minutos
        </duracion>
        <genero>
            Suspenso, misterio
        </genero>
        <anoPublicacion>
            1960
        </anoPublicacion>
        <formato>
            DVD
        </formato>
      </pelicula>
      
      <pelicula>
        <codigoPelicula>6</codigoPelicula>
        <director>
            Stanley Kubrick
        </director>
        <titulo>
            A Clockwork Orange
        </titulo>
        <duracion>
            136 minutos
        </duracion>
        <genero>
            Ciencia ficción, crimen
        </genero>
        <anoPublicacion>
            1971
        </anoPublicacion>
        <formato>
            Blu-ray
        </formato>
      </pelicula>
      
      <pelicula>
        <codigoPelicula>7</codigoPelicula>
        <director>
            Martin Scorsese
        </director>
        <titulo>
            Taxi Driver
        </titulo>
        <duracion>
            113 minutos
        </duracion>
        <genero>
            Drama, crimen
        </genero>
        <anoPublicacion>
            1976
        </anoPublicacion>
        <formato>
            DVD
        </formato>
      </pelicula>
      
      <pelicula>
        <codigoPelicula>8</codigoPelicula>
        <director>
            David Fincher
        </director>
        <titulo>
            Fight Club
        </titulo>
        <duracion>
            139 minutos
        </duracion>
        <genero>
            Drama, acción
        </genero>
        <anoPublicacion>
            1999
        </anoPublicacion>
        <formato>
            Blu-ray
        </formato>
      </pelicula>
      
      <pelicula>
        <codigoPelicula>9</codigoPelicula>
        <director>
            Ridley Scott
        </director>
        <titulo>
            Blade Runner
        </titulo>
        <duracion>
            117 minutos
        </duracion>
        <genero>
            Ciencia ficción, suspenso
        </genero>
        <anoPublicacion>
            1982
        </anoPublicacion>
        <formato>
            DVD
        </formato>
      </pelicula>
      
      <pelicula>
        <codigoPelicula>10</codigoPelicula>
        <director>
            Steven Spielberg
        </director>
        <titulo>
            Jurassic Park
        </titulo>
        <duracion>
            127 minutos
        </duracion>
        <genero>
            Ciencia ficción, aventuras
        </genero>
        <anoPublicacion>
            1993
        </anoPublicacion>
        <formato>
            Blu-ray
        </formato>
      </pelicula>

</videoclub>
