=== rbordel2102/XMLRepo/Act 4.7/Editorial/editorial.dtd
<!ELEMENT EdicionesAranda (InformeRegionalVentas)>
<!ELEMENT InformeRegionalVentas (Descripcion, Region)>
<!ATTLIST InformeRegionalVentas fecha CDATA #REQUIRED>
<!ELEMENT Descripcion (#PCDATA)>
<!ELEMENT Region (Norte, Centro, Sur)>
<!ELEMENT Norte (Trimestre1, Trimestre2, Trimestre3, Trimestre4)>
<!ELEMENT Centro (Trimestre1, Trimestre2, Trimestre3, Trimestre4)>
<!ELEMENT Sur (Trimestre1, Trimestre2, Trimestre3, Trimestre4)>
<!ELEMENT Trimestre1 (librosVendidos)>
<!ELEMENT Trimestre2 (librosVendidos)>
<!ELEMENT Trimestre3 (librosVendidos)>
<!ELEMENT Trimestre4 (librosVendidos)>
<!ELEMENT librosVendidos (#PCDATA)>

=== rbordel2102/XMLRepo/Act 4.7/Editorial/editorial_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE EdicionesAranda SYSTEM "./editorial.dtd">
<EdicionesAranda>
    <InformeRegionalVentas fecha = "30/12/2009">
    <Descripcion>Informe de ventas para las regiones Norte, Centro y Sur</Descripcion>
        <Region>
            <Norte>
                <Trimestres>

                    <Trimestre1>
                        <librosVendidos>24000</librosVendidos>
                    </Trimestre1>

                    <Trimestre2>
                        <librosVendidos>38600</librosVendidos>
                    </Trimestre2>

                    <Trimestre3>
                        <librosVendidos></librosVendidos>
                    </Trimestre3>

                    <Trimestre4>
                        <librosVendidos></librosVendidos>
                    </Trimestre4>

                </Trimestres>
            </Norte>

            <Centro>
                <Trimestres>
                    <Trimestre1>
                        <librosVendidos></librosVendidos>
                    </Trimestre1>

                    <Trimestre2>
                        <librosVendidos>16080</librosVendidos>
                    </Trimestre2>

                    <Trimestre3>
                        <librosVendidos>25000</librosVendidos>
                    </Trimestre3>

                    <Trimestre4>
                        <librosVendidos>29000</librosVendidos>
                    </Trimestre4>

                </Trimestres>
            </Centro>

            <Sur>
                <Trimestres>
                    <Trimestre1>
                        <librosVendidos>27000</librosVendidos>
                    </Trimestre1>

                    <Trimestre2>
                        <librosVendidos>31400</librosVendidos>
                    </Trimestre2>

                    <Trimestre3>
                        <librosVendidos>40100</librosVendidos>
                    </Trimestre3>

                    <Trimestre4>
                        <librosVendidos>30000</librosVendidos>
                    </Trimestre4>
                </Trimestres>
            </Sur>
        </Region>
    </InformeRegionalVentas>
</EdicionesAranda>
