=== rbordel2102/XMLRepo/Act 4.7/Pedidos/pedidos.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="PedidoCompra">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Cliente">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Direccion">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="calle" type="xs:string"/>
                                        <xs:element name="ciudad" type="xs:string"/>
                                        <xs:element name="codigoPostal" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="nombre" type="xs:string" use="required"/>
                        <xs:attribute name="email" type="xs:string" use="required"/>
                        <xs:attribute name="telefono" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Productos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Producto" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Detalles" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="codigo" type="xs:string" use="required"/>
                                    <xs:attribute name="cantidad" type="xs:integer" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Total" type="xs:decimal"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== rbordel2102/XMLRepo/Act 4.7/Pedidos/pedidos_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<PedidoCompra xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="pedidos.xsd">
    <Cliente nombre="Juan Perez" email="juanperez@gmail.com" telefono="123456789">
        <Direccion>
            <calle>Blas Infante</calle>
            <ciudad>Madrid</ciudad>
            <codigoPostal>28080</codigoPostal>
        </Direccion>
    </Cliente>
    <Productos>
        <Producto codigo="123" cantidad="2">
            <Detalles>Libro de Programaci√≥n - Autor: John Doe</Detalles>
        </Producto>
        <Producto codigo="456" cantidad="1">
            <Detalles>Manual de Uso - Autor: Jane Smith</Detalles>
        </Producto>
    </Productos>
    <Total>500</Total>
</PedidoCompra>
