=== rbordel2102/XMLRepo/Act 4.6/Proyecto/proyecto.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="proyectos" type="ProyectosType"/>

  <xs:complexType name="ProyectosType">
    <xs:sequence>
      <xs:element name="proyecto" type="ProyectoType" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ProyectoType">
    <xs:sequence>
      <xs:element name="nombre" type="xs:string"/>
      <xs:element name="responsable" type="xs:string"/>
      <xs:element name="descripcion" type="xs:string"/>
      <xs:element name="tareas" type="TareasType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TareasType">
    <xs:sequence>
      <xs:element name="tarea" type="TareaType" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TareaType">
    <xs:sequence>
      <xs:element name="nombre" type="xs:string"/>
      <xs:element name="prioridad" type="xs:string"/>
      <xs:element name="estado" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== rbordel2102/XMLRepo/Act 4.6/Proyecto/proyecto_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<proyectos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="proyecto.xsd" >
    <proyecto>
        <nombre>Sistema de Gestión de Tareas</nombre>
        <responsable>Juan Pérez</responsable>
        <descripcion>Desarrollo de una aplicación web para la gestión eficiente de tareas y proyectos.</descripcion>
        <tareas>
            <tarea>
                <nombre>Implementar base de datos</nombre>
                <prioridad>Alta</prioridad>
                <estado>En progreso</estado>
            </tarea>
            <tarea>
                <nombre>Diseñar interfaz de usuario</nombre>
                <prioridad>Media</prioridad>
                <estado>Pendiente</estado>
            </tarea>
        </tareas>
    </proyecto>

    <proyecto>
        <nombre>Aplicación Móvil de Noticias</nombre>
        <responsable>Maria González</responsable>
        <descripcion>Desarrollo de una aplicación móvil para la visualización de noticias de última hora.</descripcion>
        <tareas>
            <tarea>
                <nombre>Integrar API de noticias</nombre>
                <prioridad>Alta</prioridad>
                <estado>Pendiente</estado>
            </tarea>
            <tarea>
                <nombre>Implementar funcionalidad de búsqueda</nombre>
                <prioridad>Baja</prioridad>
                <estado>En progreso</estado>
            </tarea>
        </tareas>
    </proyecto>

</proyectos>
